[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "My 1st Python project"
authors = ["mkost148 <mkost148@gmail.com>"]
 packages = [
  { include = "brain_games" },
]

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.games.brain_even:even"
brain-calc = "brain_games.games.brain_calc:calc"
brain-gcd = "brain_games.games.brain_gcd:gcd"
brain-progression = "brain_games.brain_progression:progss"
brain-go = "brain_games.brain_go:main"

[tool.poetry.dependencies]
python = "^3.10"
prompt = "^0.4.1"


[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
